feat: enhance download script to support pkg installation on macOS
Resolves #8

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -7,14 +7,16 @@ source "$(dirname "$0")/../lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+# Determine proper extension for the requested version (tar.gz or pkg)
+ext=$(get_release_ext "$ASDF_INSTALL_VERSION")
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.$ext"
 
-# Download tar.gz file to the download directory
+# Download release file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-# Extract contents of tar.gz file into the download directory
-tar -zxvf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
-
-# Remove the tar.gz file since we don't need to keep it
-rm "$release_file"
+# If the downloaded file is a tarball, extract it; for pkg on macOS leave it as-is
+if [ "$ext" = "tar.gz" ]; then
+  tar -zxvf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+  # Remove the tar.gz file since we don't need to keep it
+  rm "$release_file"
+fi
